name: eks-demo

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to ECR
        id: build-image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.KUBERNETES_CLUSTER_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Decode Kubeconfig
        run: echo "${{ secrets.KUBERNETES_CONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

      - name: Update Kubernetes deployment
        run: |
          kubectl apply -f kubernetes/deployment.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/my-app-deployment

